type: agent
id: simple_code

name: Simple Code

description: Agent designed for simple tasks using built-in plan and code flow.

icon: glyphs-poly:code
main_agent: true

cli:
  - cli: agy
    model: gemini-3.7-flash-low
  - cli: opencode
    model: zai-coding-plan/glm-5.3/high

run_dirs:
  - /home/user/src

mount_dirs:
  readonly: []
  readwrite: []
