type: agent
id: simple_code

name: Simple Code

description: Agent designed for simple tasks using built-in plan and code flow.

icon: glyphs-poly:code
main_agent: true

cli:
  - cli: agy
    model: gemini-3.8-flash-low
  - cli: agy
    model: gemini-3.8-flash-medium
  - cli: agy
    model: gemini-3.8-flash-high
  - cli: opencode
    model: zai-coding-plan/glm-5.3/low
  - cli: opencode
    model: zai-coding-plan/glm-5.3/high
  - cli: opencode
    model: zai-coding-plan/glm-5.3-flash/high
  - cli: simplest
    model: deepseek/deepseek-v4-flash
  - cli: simplest
    model: deepseek/deepseek-v4-pro
  - cli: simplest
    model: google/gemini-3.8-flash

run_dirs:
  - /home/user/src

mount_dirs:
  readonly: []
  readwrite: []
