id: son
name: Son Agent
description: Son agent responsible for performing tasks assigned by the father agent.
icon: noto:boy
main_agent: true
cli:
- cli: agy
  model: gemini-3.6-flash-low
run_dirs:
- /tmp
mount_dirs:
  readonly: []
  readwrite: []
