id: default
name: Default Agent
description: Default agent using /tmp as run directory.
icon: fluent-color:bot-sparkle-20
cli:
  - cli: agy
    model: gemini-3.6-flash-low
  # - cli: opencode
  #   model: zai-coding-plan/glm-4.7
run_dirs:
- /tmp
mount_dirs:
  readonly: []
  readwrite: []
