type: agent
id: default
name: Default Agent
description: Default agent using /tmp as run directory.
icon: fluent-color:bot-sparkle-20
main_agent: true
cli:
  - cli: agy
    model: gemini-3.8-flash-low
  - cli: simplest
    model: zai-coding-plan/glm-5.3-flash/high
  - cli: simplest
    model: deepseek/dsv4-flash
run_dirs:
- /tmp
mount_dirs:
  readonly: []
  readwrite: []
