type: agent
id: default
name: Default Agent
description: Default agent using /tmp as run directory.
icon: fluent-color:bot-sparkle-20
main_agent: true
cli:
  - cli: agy
    model: gemini-3.7-flash-low
  - cli: opencode
    model: zai-coding-plan/glm-5.2
run_dirs:
- /tmp
mount_dirs:
  readonly: []
  readwrite: []
