id: agent_father
name: Agent Father
description: The agent creates other agents.
icon: noto:person-beard
cli:
- cli: agy
  model: gemini-3.6-flash-low
run_dirs:
- /home/user/asgard/agents
mount_dirs:
  readonly: []
  readwrite: []
