id: coder
name: Coder Agent
description: Expert Software Development Engineer responsible for feature coding, bug fixing, and passing Quality Gate checks.
type: agent
main_agent: false
cli:
  - cli: agy
    model: gemini-3.7-flash-low
  - cli: opencode
    model: zai-coding-plan/glm-5.3/low

icon: logos:geekbot
